Checkpoint 2
kirixh/ConsoleWars pull request #2
Opened 2021-04-23 22:00 UTC by kirixh

2021-05-08 23:49 UTC, AlekIks requested changes
Очень круто, вы здорово постарались!

----
Сильно не хватает документирования кода и хороших комментариев. 
Паттерны работают корректно. Для зачета чекпоинта добавьте проверку pep8 в CI и пройдите её.

2021-05-08 23:49 UTC, AlekIks commented on Players/Player.py
> +        upgrade_cost = {"scout": 1, "warrior": 2}
Зачем игроку знать, какой юнит сколько стоит? Может лучше спрашивать стоимость у конкретного юнита/здания?

2021-05-08 23:49 UTC, AlekIks commented on Map.py
> +"""sc1 = Scout(0,0)
Удалите закомментированый код, пожалуйста.

2021-05-08 23:49 UTC, AlekIks commented on Map.py
> +                if tmp_map[cell[0]][cell[1] + 1] == symbol:
Повторение кода после next_cell, попробуйте его избежать. Может вынести в отдельный метод?

2021-05-08 23:49 UTC, AlekIks commented on README.md
> +Воинам можно купить ботиночки (1 монета), гоблинам - шляпки (желтого и синего цвета, 1 монета). (редактор персонажей) Любые k воинов, стоящие непрерывно в клетках, соседних по стороне, образуют армию
Оформление текста таким и должно было быть?

2021-05-08 23:49 UTC, AlekIks commented on .github/workflows/test.yml
> +    - checkpoint_2
Написали тесты и добавили в CI, вы молодец!

2021-05-13 19:29 UTC, VladKozlovskiy commented on Players/Player.py
> +        upgrade_cost = {"scout": 1, "warrior": 2}
Мы приняли такое решение чтобы не создавать объект лишний раз. Сначала делаем проверку на возможность покупки введенного наименования, и если покупка возможна, то создаем объект  и возвращаем его. Иначе пришлось бы сначала создавать объект, брать его стоимость, и если проверка не проходит, то мы выполнили лишнее действие.

2021-05-13 19:29 UTC, VladKozlovskiy commented on Map.py
> +"""sc1 = Scout(0,0)
готово

2021-05-13 19:30 UTC, VladKozlovskiy commented on Map.py
> +                if tmp_map[cell[0]][cell[1] + 1] == symbol:
Вынесли

2021-05-13 19:30 UTC, VladKozlovskiy commented on README.md
> +Воинам можно купить ботиночки (1 монета), гоблинам - шляпки (желтого и синего цвета, 1 монета). (редактор персонажей) Любые k воинов, стоящие непрерывно в клетках, соседних по стороне, образуют армию
поправили

2021-05-13 19:30 UTC, kirixh commented on .github/workflows/test.yml
> +    - checkpoint_2
Спасибо!!

2021-05-13 19:30 UTC, VladKozlovskiy commented on .github/workflows/test.yml
> +    - checkpoint_2
Спасибо!!

2021-05-15 01:59 UTC, AlekIks commented on Players/Player.py
> +        upgrade_cost = {"scout": 1, "warrior": 2}
Оно не лишнее, т.к. позволяет сохранять инкапсуляцию. 
Дополнительные классы для паттернов тоже могут показаться "лишними", однако мы создаем их, руководствуясь принципами ООП. Пожалуйста, поправьте свой код так, чтобы он тоже им соответствовал.

2021-05-15 02:00 UTC, merged